server:
  port: 0

spring:
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:main
    username: main
    password: main
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
  h2:
    console.enabled: true
  jpa:
    show-sql: TRUE
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
  sql:
    init:
      mode: always

hibernate:
  show_sql: TRUE

logging:
  ru:
    practicum: TRACE