server:
  port: 0

spring:
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5503/request
    username: request
    password: request
  sql:
    init:
      mode: always
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: UTC
  cloud:
    openfeign:
      okhttp:
        enabled: true