server:
  port: 0

spring:
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:main
    username: main
    password: main
  h2:
    console.enabled: true
  jpa:
    show-sql: TRUE
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
  sql:
    init:
      mode: always

hibernate:
  show_sql: TRUE
  jdbc:
    time_zone: UTC

logging:
  ru:
    practicum: TRACE